import type { WeChatTheme } from "./types";
import { createHeading } from "./utils";

export const chineseTheme: WeChatTheme = {
  id: "chinese",
  name: "Chinese",
  colors: {
    primary: "#c45c26",
    text: "#2b2b2b",
    secondaryText: "#6b6b6b",
    background: "#ffffff",
    border: "#e8e0d8",
    quoteBackground: "#fff8f2",
    codeBackground: "#f7f4f0",
  },
  typography: {
    fontFamily:
      '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans SC", sans-serif',
    fontSize: 17,
    lineHeight: 1.9,
    letterSpacing: 0.8,
  },
  layout: {
    maxWidth: 680,
    contentPadding: "0",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 18,
  },
  h1: createHeading({
    fontSize: 26,
    fontWeight: 700,
    color: "#1a1a1a",
    align: "center",
    marginTop: 36,
    marginBottom: 22,
    variant: "plain",
    decoration: "none",
  }),
  h2: createHeading({
    fontSize: 21,
    fontWeight: 700,
    color: "#c45c26",
    align: "center",
    marginTop: 48,
    marginBottom: 28,
    variant: "plain",
    decoration: "band",
  }),
  h3: createHeading({
    fontSize: 18,
    fontWeight: 600,
    color: "#6b6b6b",
    align: "left",
    marginTop: 32,
    marginBottom: 14,
    variant: "plain",
    decoration: "prefix",
  }),
  h4: createHeading({
    fontSize: 16,
    fontWeight: 600,
    color: "#777777",
    marginTop: 22,
    marginBottom: 10,
    variant: "plain",
  }),
  h5: createHeading({
    fontSize: 15,
    fontWeight: 600,
    color: "#888888",
    marginTop: 18,
    marginBottom: 8,
    variant: "plain",
  }),
  h6: createHeading({
    fontSize: 14,
    fontWeight: 600,
    color: "#999999",
    marginTop: 16,
    marginBottom: 8,
    variant: "plain",
  }),
  quote: {
    padding: "14px 16px",
    marginTop: 18,
    marginBottom: 18,
    background: "#fff8f2",
    borderLeft: "4px solid #c45c26",
    borderRadius: 4,
    color: "#5a5a5a",
  },
  code: {
    background: "#f7f4f0",
    color: "#2b2b2b",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 13,
    padding: "14px 16px",
    borderRadius: 4,
    marginTop: 16,
    marginBottom: 16,
    lineHeight: 1.65,
    whiteSpace: "pre-wrap",
  },
  inlineCode: {
    background: "#fff1e8",
    color: "#c45c26",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 14,
    padding: "2px 6px",
    borderRadius: 3,
  },
  list: {
    marginTop: 8,
    marginBottom: 18,
    paddingLeft: 24,
    itemSpacing: 8,
  },
  link: {
    color: "#c45c26",
    textDecoration: "none",
  },
  image: {
    display: "block",
    maxWidth: "100%",
    marginTop: 18,
    marginBottom: 18,
    borderRadius: 4,
  },
  divider: {
    marginTop: 30,
    marginBottom: 30,
    borderTop: "1px solid #e8e0d8",
    width: "50%",
  },
  callout: {
    padding: "14px 16px",
    marginTop: 18,
    marginBottom: 18,
    borderRadius: 4,
    borderLeftWidth: 4,
    background: "#fff8f2",
    titleWeight: 600,
  },
  table: {
    fontSize: 14,
    borderColor: "#e8e0d8",
    headerBackground: "#fff8f2",
    cellPadding: "8px 12px",
    marginTop: 16,
    marginBottom: 16,
  },
};
