import type { WeChatTheme } from "./types";
import { createHeading } from "./utils";

export const defaultTheme: WeChatTheme = {
  id: "default",
  name: "Default",
  colors: {
    primary: "#07c160",
    text: "#333333",
    secondaryText: "#666666",
    background: "#ffffff",
    border: "#e5e5e5",
    quoteBackground: "#f7f7f9",
    codeBackground: "#f6f8fa",
  },
  typography: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: 16,
    lineHeight: 1.75,
    letterSpacing: 0.2,
  },
  layout: {
    maxWidth: 680,
    contentPadding: "0",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 16,
  },
  h1: createHeading({
    fontSize: 26,
    fontWeight: 700,
    color: "#222222",
    marginTop: 36,
    marginBottom: 18,
    variant: "plain",
    decoration: "none",
  }),
  h2: createHeading({
    fontSize: 22,
    fontWeight: 700,
    color: "#07c160",
    align: "center",
    marginTop: 48,
    marginBottom: 28,
    variant: "plain",
    decoration: "band",
  }),
  h3: createHeading({
    fontSize: 18,
    fontWeight: 600,
    color: "#666666",
    align: "left",
    marginTop: 32,
    marginBottom: 14,
    variant: "plain",
    decoration: "prefix",
  }),
  h4: createHeading({
    fontSize: 16,
    fontWeight: 600,
    color: "#777777",
    marginTop: 24,
    marginBottom: 10,
    variant: "plain",
  }),
  h5: createHeading({
    fontSize: 15,
    fontWeight: 600,
    color: "#888888",
    marginTop: 20,
    marginBottom: 8,
    variant: "plain",
  }),
  h6: createHeading({
    fontSize: 14,
    fontWeight: 600,
    color: "#999999",
    marginTop: 18,
    marginBottom: 8,
    variant: "plain",
  }),
  quote: {
    padding: "12px 16px",
    marginTop: 16,
    marginBottom: 16,
    background: "#f7f7f9",
    borderLeft: "4px solid #07c160",
    borderRadius: 4,
    color: "#555555",
  },
  code: {
    background: "#f6f8fa",
    color: "#24292f",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 13,
    padding: "14px 16px",
    borderRadius: 6,
    marginTop: 16,
    marginBottom: 16,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    border: "1px solid #eaeef2",
  },
  inlineCode: {
    background: "#f0f0f0",
    color: "#d6336c",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 13,
    padding: "2px 6px",
    borderRadius: 4,
  },
  list: {
    marginTop: 8,
    marginBottom: 16,
    paddingLeft: 24,
    itemSpacing: 6,
  },
  link: {
    color: "#07c160",
    textDecoration: "none",
  },
  image: {
    display: "block",
    maxWidth: "100%",
    marginTop: 16,
    marginBottom: 16,
    borderRadius: 4,
  },
  divider: {
    marginTop: 28,
    marginBottom: 28,
    borderTop: "1px solid #e5e5e5",
    width: "100%",
  },
  callout: {
    padding: "14px 16px",
    marginTop: 18,
    marginBottom: 18,
    borderRadius: 6,
    borderLeftWidth: 4,
    background: "#f7f7f9",
    titleWeight: 600,
  },
  table: {
    fontSize: 14,
    borderColor: "#e5e5e5",
    headerBackground: "#fafafa",
    cellPadding: "8px 10px",
    marginTop: 16,
    marginBottom: 16,
  },
};
