import type { WeChatTheme } from "./types";
import { createHeading } from "./utils";

export const elegantTheme: WeChatTheme = {
  id: "elegant",
  name: "Elegant",
  colors: {
    primary: "#8b5e3c",
    text: "#3a322c",
    secondaryText: "#7a6f66",
    background: "#fffdf9",
    border: "#e8ddd2",
    quoteBackground: "#f8f1ea",
    codeBackground: "#f4efe9",
  },
  typography: {
    fontFamily:
      '"Songti SC", "Noto Serif SC", "Source Han Serif SC", Georgia, serif',
    fontSize: 17,
    lineHeight: 1.9,
    letterSpacing: 0.5,
  },
  layout: {
    maxWidth: 680,
    contentPadding: "0",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 18,
  },
  h1: createHeading({
    fontSize: 28,
    fontWeight: 700,
    color: "#2c241e",
    align: "center",
    marginTop: 36,
    marginBottom: 24,
    variant: "plain",
    decoration: "none",
  }),
  h2: createHeading({
    fontSize: 22,
    fontWeight: 700,
    color: "#8b5e3c",
    align: "center",
    marginTop: 48,
    marginBottom: 28,
    variant: "plain",
    decoration: "band",
  }),
  h3: createHeading({
    fontSize: 18,
    fontWeight: 600,
    color: "#7a6f66",
    align: "left",
    marginTop: 32,
    marginBottom: 14,
    variant: "plain",
    decoration: "prefix",
  }),
  h4: createHeading({
    fontSize: 16,
    fontWeight: 600,
    color: "#8a8078",
    marginTop: 24,
    marginBottom: 10,
    variant: "plain",
  }),
  h5: createHeading({
    fontSize: 15,
    fontWeight: 600,
    color: "#9a9088",
    marginTop: 20,
    marginBottom: 8,
    variant: "plain",
  }),
  h6: createHeading({
    fontSize: 14,
    fontWeight: 600,
    color: "#aaa098",
    marginTop: 18,
    marginBottom: 8,
    variant: "plain",
  }),
  quote: {
    padding: "14px 18px",
    marginTop: 20,
    marginBottom: 20,
    background: "#f8f1ea",
    borderLeft: "4px solid #8b5e3c",
    borderRadius: 8,
    color: "#6a5f56",
  },
  code: {
    background: "#f4efe9",
    color: "#3a322c",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 13,
    padding: "14px 16px",
    borderRadius: 8,
    marginTop: 18,
    marginBottom: 18,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
  },
  inlineCode: {
    background: "#f0e8df",
    color: "#8b5e3c",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 14,
    padding: "2px 6px",
    borderRadius: 4,
  },
  list: {
    marginTop: 8,
    marginBottom: 18,
    paddingLeft: 24,
    itemSpacing: 8,
  },
  link: {
    color: "#8b5e3c",
    textDecoration: "underline",
  },
  image: {
    display: "block",
    maxWidth: "100%",
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 8,
  },
  divider: {
    marginTop: 32,
    marginBottom: 32,
    borderTop: "1px solid #e8ddd2",
    width: "60%",
  },
  callout: {
    padding: "14px 16px",
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 8,
    borderLeftWidth: 4,
    background: "#f8f1ea",
    titleWeight: 600,
  },
  table: {
    fontSize: 14,
    borderColor: "#e8ddd2",
    headerBackground: "#f8f1ea",
    cellPadding: "8px 12px",
    marginTop: 18,
    marginBottom: 18,
  },
};
