import type { WeChatTheme } from "./types";
import { createHeading } from "./utils";

/**
 * Fumadocs-inspired documentation prose theme.
 * Clean docs layout with soft borders, lined tables, and muted quotes.
 */
export const fumadocsTheme: WeChatTheme = {
  id: "fumadocs",
  name: "Fumadocs",
  colors: {
    primary: "#4f46e5",
    text: "#3f3f46",
    secondaryText: "#71717a",
    background: "#ffffff",
    border: "#e4e4e7",
    quoteBackground: "#fafafa",
    codeBackground: "#f4f4f5",
  },
  typography: {
    fontFamily:
      'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "PingFang SC", "Noto Sans SC", "Microsoft YaHei", sans-serif',
    fontSize: 16,
    lineHeight: 1.8,
    letterSpacing: 0.1,
  },
  layout: {
    maxWidth: 720,
    contentPadding: "0",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 18,
  },
  h1: createHeading({
    fontSize: 28,
    fontWeight: 700,
    color: "#18181b",
    align: "left",
    marginTop: 8,
    marginBottom: 22,
    variant: "plain",
    decoration: "none",
  }),
  h2: createHeading({
    fontSize: 22,
    fontWeight: 600,
    color: "#4f46e5",
    align: "center",
    marginTop: 48,
    marginBottom: 28,
    variant: "plain",
    decoration: "band",
  }),
  h3: createHeading({
    fontSize: 18,
    fontWeight: 600,
    color: "#52525b",
    align: "left",
    marginTop: 32,
    marginBottom: 14,
    variant: "plain",
    decoration: "prefix",
  }),
  h4: createHeading({
    fontSize: 16,
    fontWeight: 600,
    color: "#71717a",
    marginTop: 24,
    marginBottom: 10,
    variant: "plain",
  }),
  h5: createHeading({
    fontSize: 15,
    fontWeight: 600,
    color: "#71717a",
    marginTop: 20,
    marginBottom: 8,
    variant: "plain",
  }),
  h6: createHeading({
    fontSize: 14,
    fontWeight: 600,
    color: "#a1a1aa",
    marginTop: 18,
    marginBottom: 8,
    variant: "plain",
  }),
  quote: {
    padding: "0 0 0 16px",
    marginTop: 24,
    marginBottom: 24,
    background: "transparent",
    borderLeft: "2px solid #4f46e5",
    borderRadius: 0,
    color: "#71717a",
    fontSize: 16,
    fontStyle: "normal",
    lineHeight: 1.75,
  },
  code: {
    background: "#f4f4f5",
    color: "#18181b",
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    fontSize: 13,
    padding: "14px 16px",
    borderRadius: 10,
    marginTop: 18,
    marginBottom: 18,
    lineHeight: 1.65,
    whiteSpace: "pre-wrap",
    border: "1px solid #e4e4e7",
  },
  inlineCode: {
    background: "#f4f4f5",
    color: "#4f46e5",
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    fontSize: 13,
    padding: "2px 6px",
    borderRadius: 6,
  },
  list: {
    marginTop: 8,
    marginBottom: 18,
    paddingLeft: 22,
    itemSpacing: 6,
  },
  link: {
    color: "#4f46e5",
    textDecoration: "underline",
  },
  image: {
    display: "block",
    maxWidth: "100%",
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 10,
  },
  divider: {
    marginTop: 32,
    marginBottom: 32,
    borderTop: "1px solid #e4e4e7",
    width: "100%",
  },
  callout: {
    padding: "14px 16px",
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 10,
    borderLeftWidth: 0,
    background: "#eef2ff",
    titleWeight: 600,
    border: "1px solid #c7d2fe",
  },
  table: {
    fontSize: 14,
    borderColor: "#e4e4e7",
    headerBackground: "#fafafa",
    headerColor: "#18181b",
    cellPadding: "12px 16px",
    marginTop: 20,
    marginBottom: 20,
    variant: "lined",
    borderRadius: 10,
    stripedBackground: "#fcfcfc",
    textColor: "#3f3f46",
  },
};
