import type { WeChatTheme } from "./types";
import { createHeading } from "./utils";

export const minimalTheme: WeChatTheme = {
  id: "minimal",
  name: "Minimal",
  colors: {
    primary: "#111111",
    text: "#222222",
    secondaryText: "#777777",
    background: "#ffffff",
    border: "#dddddd",
    quoteBackground: "#fafafa",
    codeBackground: "#f5f5f5",
  },
  typography: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", sans-serif',
    fontSize: 16,
    lineHeight: 1.85,
    letterSpacing: 0.3,
  },
  layout: {
    maxWidth: 680,
    contentPadding: "0",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 20,
  },
  h1: createHeading({
    fontSize: 28,
    fontWeight: 700,
    color: "#111111",
    marginTop: 40,
    marginBottom: 24,
    variant: "plain",
    decoration: "none",
  }),
  h2: createHeading({
    fontSize: 22,
    fontWeight: 600,
    color: "#111111",
    align: "center",
    marginTop: 48,
    marginBottom: 28,
    variant: "plain",
    decoration: "band",
  }),
  h3: createHeading({
    fontSize: 18,
    fontWeight: 600,
    color: "#555555",
    align: "left",
    marginTop: 32,
    marginBottom: 14,
    variant: "plain",
    decoration: "prefix",
  }),
  h4: createHeading({
    fontSize: 16,
    fontWeight: 600,
    color: "#666666",
    marginTop: 24,
    marginBottom: 12,
    variant: "plain",
  }),
  h5: createHeading({
    fontSize: 15,
    fontWeight: 600,
    color: "#777777",
    marginTop: 20,
    marginBottom: 10,
    variant: "plain",
  }),
  h6: createHeading({
    fontSize: 14,
    fontWeight: 600,
    color: "#888888",
    marginTop: 18,
    marginBottom: 8,
    variant: "plain",
  }),
  quote: {
    padding: "12px 0 12px 16px",
    marginTop: 20,
    marginBottom: 20,
    background: "transparent",
    borderLeft: "2px solid #111111",
    borderRadius: 0,
    color: "#555555",
  },
  code: {
    background: "#f5f5f5",
    color: "#111111",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 13,
    padding: "16px",
    borderRadius: 2,
    marginTop: 20,
    marginBottom: 20,
    lineHeight: 1.65,
    whiteSpace: "pre-wrap",
  },
  inlineCode: {
    background: "#f0f0f0",
    color: "#111111",
    fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    fontSize: 13,
    padding: "2px 5px",
    borderRadius: 2,
  },
  list: {
    marginTop: 8,
    marginBottom: 20,
    paddingLeft: 22,
    itemSpacing: 8,
  },
  link: {
    color: "#111111",
    textDecoration: "underline",
  },
  image: {
    display: "block",
    maxWidth: "100%",
    marginTop: 24,
    marginBottom: 24,
    borderRadius: 0,
  },
  divider: {
    marginTop: 36,
    marginBottom: 36,
    borderTop: "1px solid #dddddd",
    width: "40%",
  },
  callout: {
    padding: "14px 16px",
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 2,
    borderLeftWidth: 2,
    background: "#fafafa",
    titleWeight: 600,
  },
  table: {
    fontSize: 13,
    borderColor: "#dddddd",
    headerBackground: "#fafafa",
    cellPadding: "8px 10px",
    marginTop: 20,
    marginBottom: 20,
  },
};
