import type { ShadcnPalette } from "./shadcn";

/**
 * Dark counterparts for each shadcn publish palette.
 * Hex values are fixed (not Obsidian CSS vars) so preview/copy stay consistent.
 */
export const SHADCN_DARK_PALETTES: ShadcnPalette[] = [
  {
    id: "zinc",
    name: "Zinc",
    primary: "#fafafa",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#27272a",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
  },
  {
    id: "slate",
    name: "Slate",
    primary: "#f8fafc",
    foreground: "#f8fafc",
    foregroundMuted: "#94a3b8",
    heading: "#f8fafc",
    headingMuted: "#e2e8f0",
    border: "#1e293b",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    background: "#020617",
    cardHeader: "#0f172a",
  },
  {
    id: "stone",
    name: "Stone",
    primary: "#fafaf9",
    foreground: "#fafaf9",
    foregroundMuted: "#a8a29e",
    heading: "#fafaf9",
    headingMuted: "#e7e5e4",
    border: "#292524",
    muted: "#292524",
    mutedForeground: "#a8a29e",
    background: "#0c0a09",
    cardHeader: "#1c1917",
  },
  {
    id: "gray",
    name: "Gray",
    primary: "#f9fafb",
    foreground: "#f9fafb",
    foregroundMuted: "#9ca3af",
    heading: "#f9fafb",
    headingMuted: "#e5e7eb",
    border: "#1f2937",
    muted: "#1f2937",
    mutedForeground: "#9ca3af",
    background: "#030712",
    cardHeader: "#111827",
  },
  {
    id: "neutral",
    name: "Neutral",
    primary: "#fafafa",
    foreground: "#fafafa",
    foregroundMuted: "#a3a3a3",
    heading: "#fafafa",
    headingMuted: "#e5e5e5",
    border: "#262626",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    background: "#0a0a0a",
    cardHeader: "#171717",
  },
  {
    id: "blue",
    name: "Blue",
    primary: "#60a5fa",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#172554",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#3b82f6",
  },
  {
    id: "green",
    name: "Green",
    primary: "#4ade80",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#14532d",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#22c55e",
  },
  {
    id: "violet",
    name: "Violet",
    primary: "#a78bfa",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#2e1065",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#8b5cf6",
  },
  {
    id: "orange",
    name: "Orange",
    primary: "#fb923c",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#7c2d12",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#f97316",
  },
  {
    id: "rose",
    name: "Rose",
    primary: "#fb7185",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#881337",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#f43f5e",
  },
  {
    id: "teal",
    name: "Teal",
    primary: "#2dd4bf",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#134e4a",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#14b8a6",
  },
  {
    id: "red",
    name: "Red",
    primary: "#f87171",
    foreground: "#fafafa",
    foregroundMuted: "#a1a1aa",
    heading: "#fafafa",
    headingMuted: "#e4e4e7",
    border: "#27272a",
    muted: "#7f1d1d",
    mutedForeground: "#a1a1aa",
    background: "#09090b",
    cardHeader: "#18181b",
    ring: "#ef4444",
  },
];

export function getShadcnDarkPalette(colorId: string): ShadcnPalette | undefined {
  return SHADCN_DARK_PALETTES.find((p) => p.id === colorId);
}
