import type { WeChatTheme } from "./types";
import { createHeading } from "./utils";

export const techTheme: WeChatTheme = {
  id: "tech",
  name: "Tech",
  colors: {
    primary: "#625fff",
    text: "#1f2430",
    secondaryText: "#5c6578",
    background: "#ffffff",
    border: "#e3e7ef",
    quoteBackground: "#f3f4ff",
    codeBackground: "#0f172a",
  },
  typography: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", "PingFang SC", "Segoe UI", sans-serif',
    fontSize: 16,
    lineHeight: 1.75,
    letterSpacing: 0.1,
  },
  layout: {
    maxWidth: 680,
    contentPadding: "0",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 16,
  },
  h1: createHeading({
    fontSize: 26,
    fontWeight: 700,
    color: "#111827",
    marginTop: 36,
    marginBottom: 18,
    variant: "plain",
    decoration: "none",
  }),
  h2: createHeading({
    fontSize: 20,
    fontWeight: 700,
    color: "#625fff",
    align: "center",
    marginTop: 48,
    marginBottom: 28,
    variant: "plain",
    decoration: "band",
  }),
  h3: createHeading({
    fontSize: 17,
    fontWeight: 600,
    color: "#5c6578",
    align: "left",
    marginTop: 32,
    marginBottom: 14,
    variant: "plain",
    decoration: "prefix",
  }),
  h4: createHeading({
    fontSize: 15,
    fontWeight: 600,
    color: "#64748b",
    marginTop: 22,
    marginBottom: 10,
    variant: "plain",
  }),
  h5: createHeading({
    fontSize: 14,
    fontWeight: 600,
    color: "#64748b",
    marginTop: 18,
    marginBottom: 8,
    variant: "plain",
  }),
  h6: createHeading({
    fontSize: 13,
    fontWeight: 600,
    color: "#94a3b8",
    marginTop: 16,
    marginBottom: 8,
    variant: "plain",
  }),
  quote: {
    padding: "12px 16px",
    marginTop: 16,
    marginBottom: 16,
    background: "#f3f4ff",
    borderLeft: "4px solid #625fff",
    borderRadius: 6,
    color: "#4b5568",
  },
  code: {
    background: "#0f172a",
    color: "#e2e8f0",
    fontFamily: '"JetBrains Mono", Menlo, Monaco, Consolas, monospace',
    fontSize: 13,
    padding: "14px 16px",
    borderRadius: 8,
    marginTop: 16,
    marginBottom: 16,
    lineHeight: 1.65,
    whiteSpace: "pre-wrap",
    border: "1px solid #1e293b",
  },
  inlineCode: {
    background: "#eef0ff",
    color: "#4f46e5",
    fontFamily: '"JetBrains Mono", Menlo, Monaco, Consolas, monospace',
    fontSize: 13,
    padding: "2px 6px",
    borderRadius: 4,
  },
  list: {
    marginTop: 8,
    marginBottom: 16,
    paddingLeft: 24,
    itemSpacing: 6,
  },
  link: {
    color: "#625fff",
    textDecoration: "none",
  },
  image: {
    display: "block",
    maxWidth: "100%",
    marginTop: 16,
    marginBottom: 16,
    borderRadius: 8,
  },
  divider: {
    marginTop: 28,
    marginBottom: 28,
    borderTop: "1px solid #e3e7ef",
    width: "100%",
  },
  callout: {
    padding: "14px 16px",
    marginTop: 18,
    marginBottom: 18,
    borderRadius: 8,
    borderLeftWidth: 4,
    background: "#f3f4ff",
    titleWeight: 600,
  },
  table: {
    fontSize: 13,
    borderColor: "#e3e7ef",
    headerBackground: "#f8fafc",
    cellPadding: "8px 10px",
    marginTop: 16,
    marginBottom: 16,
  },
};
